gapfinder/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html')),
    path('section-alignment/',
         include('sectionalignment.urls', namespace="sectionalignment")),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sectionalignment/urls.py
from django.urls import path

from . import views

app_name = 'sectionalignment'

urlpatterns = [
    path('', views.index, {
        "template_name": "sectionalignment/index.html"
    }, name='index'),
    path('mapping', views.mapping, {
        "template_name": "sectionalignment/mapping.html"
    }, name='mapping'),
    path('mapping/save', views.save_mapping, name='save_mapping')
]

sectionalignment/models.py
import hashlib

from django.db import models
# from django.db.models.signals import post_save
# from django.dispatch import receiver

# import json


LANGUAGE_CHOICES = (
    ('ar', 'العربية'),
    ('en', 'English'),
    ('es', 'Español'),
    ('fr', 'Français'),
    ('ja', '日本語'),
    ('ru', 'Русский')
)


class Mapping(models.Model):
    "Mappings and user inputs"
    title = models.TextField()
    language = models.CharField(
        choices=LANGUAGE_CHOICES, db_index=True, max_length=2
    )
    # lower section_rank = section appears more frequently
    rank = models.PositiveIntegerField(db_index=True)
    # For indexing. MySQL has a limit on indexed column length.
    title_sha256 = models.CharField(max_length=64)

    class Meta:
        unique_together = (("title_sha256", "language"),)

    def __str__(self):
        return "%s: %s" % (self.language, self.title)

    def save(self, *args, **kwargs):
        self.title_sha256 = hashlib.sha256(
            self.title.encode('utf-8')).hexdigest()
        super(Mapping, self).save(*args, **kwargs)


class UserInput(models.Model):
    source = models.ForeignKey(Mapping, on_delete=models.CASCADE)
    destination_language = models.CharField(
        choices=LANGUAGE_CHOICES, db_index=True, max_length=2
    )
    # Contains the list of user's input values.
    destination_title = models.TextField()
    # Has the user filled out this mapping?
    done = models.BooleanField(db_index=True, default=False)
    # When did the user see the question?
    # If this time is more than 5 mins old, then we can show this
    # question to someone else.
    start_time = models.DateTimeField()
    user_session_key = models.CharField(max_length=64, default='')

    def __str__(self):
        return "%s - %s: %s" % (self.source.language,
                                self.destination_language,
                                self.source.title)

    class Meta:
        unique_together = (("source", "destination_language"),)

sectionalignment/views.py
from datetime import datetime, timedelta
import json

from django.conf import settings
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils import translation
from django.views.decorators.http import require_GET, require_POST

from .models import Mapping, UserInput, LANGUAGE_CHOICES


LANGUAGE_CHOICES_DICT = dict(LANGUAGE_CHOICES)


def set_new_user_session(request, source=None, destination=None):
    """Create request.session['user']."""
    user = {
        'source': source,
        'destination': destination,
        'progress': 0
    }
    for s, _ in LANGUAGE_CHOICES:
        user[s] = {}
        for d, _ in LANGUAGE_CHOICES:
            if s == d:
                continue
            user[s][d] = {
                'skipped': [],
                'question': None
            }
    request.session['user'] = user
    request.session[translation.LANGUAGE_SESSION_KEY] = destination
    request.session.modified = True


def get_user_session(request):
    """Return user data from request.session."""
    return request.session.get('user')


def set_user_session_languages(request, source, destination):
    """Set user's source and destination languages."""
    user = request.session['user']
    user['source'] = source
    user['destination'] = destination
    request.session['user'] = user
    request.session[translation.LANGUAGE_SESSION_KEY] = destination
    request.session.modified = True


def set_user_session_skipped(request,  skipped):
    """Add skipped to the list of skipped questions for source and
    destionation."""
    user = request.session['user']
    source = user['source']
    destination = user['destination']
    user[source][destination]['skipped'].append(skipped)
    request.session['user'] = user
    request.session.modified = True


def increase_user_session_progress(request):
    """Add 1 to user's progress for source and destination."""
    request.session['user']['progress'] += 1
    request.session.modified = True


def set_user_session_question(request, id):
    """Set current question ID."""
    user = request.session['user']
    source = user['source']
    destination = user['destination']
    user[source][destination]['question'] = id
    request.session['user'] = user
    request.session.modified = True


def get_user_session_question(request):
    """Return the current question ID."""
    user = request.session['user']
    source = user['source']
    destination = user['destination']
    return user[source][destination]['question']


def delete_user_session_question(request):
    """Delete question from user session."""
    user = request.session['user']
    source = user['source']
    destination = user['destination']
    user[source][destination]['question'] = None
    request.session['user'] = user
    request.session.modified = True


@require_GET
def index(request, template_name):
    """Index page
    - If 'c' GET parameter is set, clear user languages and question
      data and allow selecting languages.
    - Else if 's' (source) and 'd' (destination) are passed and
      distinct valid LANGUAGE_CHOICES, then redirect to /mapping.
    - Else if user session is already present, redirect to /mapping.
    """
    # del request.session['user']
    # request.session.modified = True
    # return HttpResponse(request.session)
    user = get_user_session(request)
    source = request.GET.get('s')
    destination = request.GET.get('d')

    if source in LANGUAGE_CHOICES_DICT and\
       destination in LANGUAGE_CHOICES_DICT and\
       source != destination:
        if user:
            set_user_session_languages(request, source, destination)
        else:
            set_new_user_session(request, source, destination)
        return HttpResponseRedirect(reverse('sectionalignment:mapping'))

    if user and not request.GET.get('c'):
        return HttpResponseRedirect(reverse('sectionalignment:mapping'))

    return render(request, template_name, {
        'languages': LANGUAGE_CHOICES_DICT
    })


@require_POST
def save_mapping(request):
    """Save mapping
    """
    user = get_user_session(request)
    question = get_user_session_question(request)
    if not user or not question:
        return HttpResponseRedirect(reverse('sectionalignment:mapping'))

    if 'skip' in request.POST:
        set_user_session_skipped(request, question)
    elif 'save' in request.POST:
        translation = request.POST.getlist('translation', [])
        translation_set = {t.strip() for t in translation if t.strip()}
        # add entry to the skipped list if no input is provided
        if not len(translation_set):
            set_user_session_skipped(request, question)
        else:
            user_input = UserInput.objects.get(pk=question)
            # this should not happen, but in case data is already there,
            # append.
            if user_input.done:
                translation_set |= set(
                    json.loads(user_input.destination_title or '')
                )
            user_input.destination_title = json.dumps(
                list(translation_set), ensure_ascii=False)
            user_input.done = True
            user_input.user_session_key = request.session.session_key
            user_input.save()
            increase_user_session_progress(request)

    # we're done with this question
    delete_user_session_question(request)

    return HttpResponseRedirect(reverse('sectionalignment:mapping'))


@require_GET
def mapping(request, template_name):
    """Show a question
    - If no user session is present, redirect to /index.
    - Else if the user refreshed the page, show the old question.
    - Else show a new question, but only if it hasn't been seen in the
      last QUESTION_DROP_MINUTES minutes.
    - Then update the question's start_time to now(), and set session
      values.
    """
    user = get_user_session(request)
    if not user:
        return HttpResponseRedirect(reverse('sectionalignment:index'))

    source = user['source']
    destination = user['destination']
    user_input = None
    question = get_user_session_question(request)

    # Has the user refreshed the page?
    if question:
        user_input = UserInput.objects.filter(
            id=question,
            source__language=user['source'],
            destination_language=user['destination'],
            done=False
        ).first()

    # Nope, the user is asking for a new question.
    if not user_input:
        user_input = UserInput.objects.filter(
            source__language=source,
            destination_language=destination,
            done=False,
            start_time__lt=datetime.now() - timedelta(
                minutes=settings.QUESTION_DROP_MINUTES)
        ).exclude(
            id__in=user[source][destination]['skipped']
        ).order_by('source__rank').first()

    # save start time so someone else doesn't take the same question
    if user_input:
        user_input.start_time = datetime.now()
        user_input.user_session_key = request.session.session_key
        user_input.save()
        set_user_session_question(request, user_input.id)

    # autocomplete suggestions
    suggestions = Mapping.objects\
                         .filter(language=user['destination'])\
                         .values_list('title', flat=True)

    return render(request, template_name, {
        'source': {
            'code': user['source'],
            'title': LANGUAGE_CHOICES_DICT[user['source']]
        },
        'destination': {
            'code': user['destination'],
            'title': LANGUAGE_CHOICES_DICT[user['destination']]
        },
        'user': user,
        'user_input': user_input,
        'suggestions': list(suggestions),
        'language_choices_dict': LANGUAGE_CHOICES_DICT
    })

sectionalignment/templates/sectionalignment/base.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{# Translators: Name of the window title #}
{% trans "Section Alignment" %}
{% endblock %}

{% block header %}
<div class="row">
    <div class="col">
        <h2>
            {# Translators: Site branding #}
            {% trans "WikipediA Research" %}
        </h2>
    </div>
</div>
{% endblock %}

sectionalignment/templates/sectionalignment/index.html
{% extends "sectionalignment/base.html" %}
{% load static %}
{% load i18n %}

{% block extra_scripts %}
<script src="{% static "sectionalignment/js/index.js" %}" ></script>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-9 col-lg-7">
        <div class="main-content">
            <form action="{% url 'sectionalignment:index' %}" method="get">
                <div class="row">
                    <div class="col">
                        <p>
                            {# Translators: Call to action #}
                            {% trans "Please select languages to start translating section titles." %}
                        </p>
                        <div class="alert alert-danger error {% if not error_message %}d-none{% endif %}" role="alert">
                            {{ error_message }}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-7">
                        <label for="s">
                            {# Translators: Language to translate section titles from #}
                            {% trans "Source Language" %}
                        </label>
                        <select id="s" name="s" class="form-control">
                            <option value="" selected="selected"></option>
                            {% for code, language in languages.items %}
                            <option value="{{ code }}">{{ language }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-7">
                        <label for="d">
                            {# Translators: Language to translate section titles to #}
                            {% trans "Destination Language" %}
                        </label>
                        <select id="d" name="d" class="form-control">
                            <option value="" selected="selected"></option>
                            {% for code, language in languages.items %}
                            <option value="{{ code }}">{{ language }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="text-right">
                    <button type="submit" class="btn btn-primary">
                        {# Translators: Label of the button that takes the user to the mapping page #}
                        {% trans "Start" %}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

sectionalignment/templates/sectionalignment/mapping.html
{% extends "sectionalignment/base.html" %}
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_current_language_bidi as LANGUAGE_BIDI %}

{% block extra_styles %}
{% if LANGUAGE_BIDI %}
<link rel="stylesheet" href="{% static "sectionalignment/css/mapping_rtl.css" %}">
<link rel="stylesheet" href="{% static "css/easy-autocomplete.min_rtl.css" %}">
{% else %}
<link rel="stylesheet" href="{% static "sectionalignment/css/mapping.css" %}">
<link rel="stylesheet" href="{% static "css/easy-autocomplete.min.css" %}">
{% endif %}
{% endblock %}

{% block extra_scripts %}
<script>
GT.suggestions = {{ suggestions|safe }};
GT.userProgress = {{ user.progess|default:0 }};
</script>
<script src="{% static "js/jquery.easy-autocomplete.min.js" %}"></script>
<script src="{% static "sectionalignment/js/mapping.js" %}"></script>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-9 col-lg-7">
        <b>
            {# Translators: Call to action heading #}
            {% trans "Translate section titles to train our robots" %}
        </b>
        <p>
            {# Translators: Explanation of the task to translators #}
            {% trans "Translate these section titles as you would expect to find them on Wikipedia articles in your language. If, depending on context, a section title can have multiple translations in your Wikipedia language, provide all translations. Use suggestions by auto-complete feature or write your own translation. If you don't know a translation or a translation doesn't exist, skip. The more you translate the better suggestions we'll be able to provide to editors in the future." %}
        </p>
        <!-- <br> -->
        <!-- <a href="#">More instructions</a> -->

        <div class="row">
            <div class="col-md-7 col-lg-7">
                <div class="btn-group source">
                    <button type="button" id="source-language" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ source.title }}
                    </button>
                    <div class="dropdown-menu" aria-labelledby="source-language">
                        {% for code, name in language_choices_dict.items %}
                        <a class="dropdown-item"
                           href="{% url "sectionalignment:index" %}?{% if code != destination.code %}s={{ code }}&d={{ destination.code }}{% else %}s={{ destination.code }}&d={{ source.code }}{% endif %}">
                            {{name}}
                        </a>
                        {% endfor %}
                    </div>
                </div>
                <span class="arrow-box"></span>
                <div class="btn-group destination">
                    <button type="button" id="destination-language" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ destination.title }}
                    </button>
                    <div class="dropdown-menu" aria-labelledby="destination-language">
                        {% for code, name in language_choices_dict.items %}
                        <a class="dropdown-item"
                           href="{% url "sectionalignment:index" %}?{% if code != source.code %}s={{ source.code }}&d={{ code }}{% else %}s={{ destination.code }}&d={{ source.code }}{% endif %}">
                            {{name}}
                        </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-md-5 text-right">
                {% if user.progress > 4 %}
                {% if user.progress > 100 %}
                🤓
                {% elif user.progress > 50 %}
                😎
                {% elif user.progress > 25 %}
                😁
                {% elif user.progress > 4 %}
                😀
                {% endif %}
                {# Translators: Message indicating progress. N is the number of translations completed by the user. N is always bigger than 4.#}
                {% blocktrans with N=user.progress %}{{ N }} translations completed!{% endblocktrans %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% if user_input %}
<div class="row">
    <div class="col-md-9 col-lg-7">
        <br>
        <div class="alert alert-danger error d-none" role="alert">
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-9 col-lg-7">
        <div class="question main-content">
            <b>
                {# Translators: Label for the section title in source language #}
                {% trans "Section to translate" %}
            </b>
            <h2>{{ user_input.source.title }}</h2>
            <!-- <a href="">View example</a> -->
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-9 col-lg-7">
        <form action="{% url 'sectionalignment:save_mapping' %}" method="post">
            <div class="answer main-content form-group">
                <div>
                    {# Translators: Label for the input in destination language #}
                    {% trans "Your translation" %}
                </div>
                {% csrf_token %}
                <div class="translation-box">
                    <input type="text" class="translation form-control" name="translation" autofocus>
                </div>
                <button id="add-more" type="button" class="btn btn-link">
                    {# Translators: Button label #}
                    {% trans "+ Add an alternative translation" %}
                </button>
                <div class="text-right">
                    <!-- order is important, we want the save button to submit by default -->
                    <button type="submit" class="btn btn-primary float-right" name="save">
                        {# Translators: Button label #}
                        {% trans "Submit translation" %}
                    </button>
                    <button type="submit" class="btn btn-secondary" name="skip">
                        {# Translators: Button label #}
                        {% trans "Skip this one" %}
                    </button>&nbsp;
                    <div class="clearfix"></div>
                </div>
            </div>
        </form>
    </div>
</div>
{% else %}
<div class="row">
    <div class="col-md-9 col-lg-7">
        <div class="main-content">
            {# Translators: Message shown when all translation tasks are complete. #}
            {% trans "✌ No more sections to map!" %}
        </div>
    </div>
</div>
{% endif %}

{% endblock %}