gapfinder/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html')),
    path('section-alignment/',
         include('sectionalignment.urls', namespace="sectionalignment")),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sectionalignment/urls.py
from django.urls import path

from . import views

app_name = 'sectionalignment'

urlpatterns = [
    path('', views.index, {
        "template_name": "sectionalignment/index.html"
    }, name='index'),
    path('mapping', views.mapping, {
        "template_name": "sectionalignment/mapping.html"
    }, name='mapping'),
    path('mapping/save', views.save_mapping, name='save_mapping')
]

templates/base.html
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
<!DOCTYPE html>
<html class="no-js" lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}gapfinder tools{% endblock %}</title>

        {% if LANGUAGE_BIDI %}
        <link rel="stylesheet" href="{% static "css/base_rtl.css" %}">
        <link rel="stylesheet" href="{% static "css/bootstrap.min_rtl.css" %}">
        {% else %}
        <link rel="stylesheet" href="{% static "css/base.css" %}">
        <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
        {% endif %}
        {% block extra_styles %}{% endblock %}
    </head>
    <body>
        <div class="container">
            <header>
                {% block header %}
                <div class="row">
                    <div class="col">
                        <a href="/" class="project-name">
                            {# Translators: Site branding #}
                            {% trans "WikipediA Research" %}
                        </a>
                        <span class="app-name">{% block appname %}{% endblock %}</span>
                    </div>
                </div>
                {% endblock %}
            </header>
            <main>
                {% block content %}
                {% endblock %}
            </main>
            <footer>
                {% block footer %}
                {% endblock %}
            </footer>
        </div>

        <script src="{% static "js/jquery-3.3.1.min.js" %}"></script>
        <script src="{% static "js/popper.min.js" %}"></script>
        <script src="{% static "js/bootstrap.min.js" %}"></script>
        <script src="{% static "js/base.js" %}"></script>
        {% block extra_scripts %}{% endblock %}
    </body>
</html>

templates/index.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
<div class="row">
    <div class="col-md-7">
        <h3>
            {# Translators: Header for the list of apps supported by Gapfindertools #}
            {% trans "Apps" %}
        </h3>
        <ul>
            <li><a href="{% url "sectionalignment:index" %}">{% trans "section alignment" %}</a></li>
        </ul>
    </div>
</div>
{% endblock %}